// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdsbccbqabbzpwvurkzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkc2JjY2JxYWJienB3dnVya3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDkxMDAsImV4cCI6MjA2NTk4NTEwMH0.LEG5R9T0daqS9URhgucxlmDEKZuGDG-Br5pQCUE8vqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);